language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  include:
    - os: windows
      arch: x64
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.0
    - os: windows
      arch: x64
      julia: 1.1
    - os: windows
      arch: x86
      julia: 1.1
  allow_failures:
    - julia: nightly
    - arch: x86

script:
  - julia --color=yes --code-coverage --inline=no runtests.jl
  - ./bin/check_notebooks
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - ./bin/configlet tree . --with-difficulty

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder("exercises"))'
