language: julia

os:
  - linux
  - osx

julia:
  - release
  - nightly
  - 0.5

matrix:
  allow_failures:
    - julia: nightly

script:
  - julia runtests.jl
  - ./bin/fetch-configlet
  - ./bin/configlet .
