language: julia

os:
  - linux

julia:
  - nightly
  - 0.6

matrix:
  allow_failures:
    - julia: nightly

script:
  - julia runtests.jl
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - ./bin/configlet tree . --with-difficulty
