language: julia

os:
  - linux
  - windows

arch:
  - x86
  - arm64

julia:
  - 1.0 # lts
  - 1.2
  - 1.3
  - nightly

matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  exclude:
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64
  allow_failures:
    - arch: x86

script:
  - julia --color=yes --code-coverage --inline=no runtests.jl
  - ./bin/check_notebooks
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - ./bin/configlet tree . --with-difficulty

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder("exercises"))'
