name: Check Notebooks

on:
  push:
    branches: master
  pull_request:

jobs:
  check_notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1

    - name: Check Notebooks
      run: ./bin/check_notebooks
